spring:
  application:
    name: yd-yx-manage
server:
  port: 9000
# 安全失效
management:
  security:
    enabled: false
# 取消服务器自我注册
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    healthcheck:
      enabled: true
# 服务用于注册
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka
    registry-fetch-interval-seconds: 30
  server:
    enable-self-preservatioin: false
    renewal-percent-threshold: 0.8
    eviction-interval-timer-in-ms: 1000
    user-read-only-cache: false
    response-cache-update-interval-ms: 1000
  instance:
    lease-renewal-interval-in-seconds: 30
