spring:
  application:
    name: usermessage-consumer
  resources:
    static-locations: /templates/**
  mvc:
    static-path-pattern: /templates/**
  #模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML5
    cache: false
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
server:
  port: 4475
  servlet:
    context-path: /${spring.application.name}
# 安全失效
management:
  security:
    enabled: false
# 取消服务器自我注册
eureka:
# 服务用于注册
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

security:
  oauth2:
    client:
      client-id: ${spring.application.name}
      client-secret: test1111
      user-authorization-uri: http://127.0.0.1:1113/oauth/authorize
      access-token-uri: http://127.0.0.1:1113/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:1113/oauth/token_key


