##https://www.cnblogs.com/niejunlei/p/5977895.html
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usershiro?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    minEvictableTimeMillis: 300000
    validationQuery: select * from userdata
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #filters: stat,wall,log4j
    filters: stat,wall,shiroFilter
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat=true
  mvc:
    view:
      suffix: .jsp
      prefix: jsp/
  thymeleaf:
    cache: false
    enabled: false
## mybatis
mybatis:
  typeAliasesPackage: com.shiro.pojo
  mapperLocations: classpath:mybatis/*.xml