server:
  port: 1112
spring:
  application:
    name: usermessage-provider
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/usershiro?serverTimezone=GMT%2B8
    username: root
    password: 123456

# 安全失效
management:
  security:
    enabled: false
# 取消服务器自我注册
eureka:
  server:
    port: 9090
# 服务用于注册
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

jwt:
  expire: 10

# 配置hystrix的参数
hystrix:
  threadpool:
    # default: 默认参数，作用的所有的hystrix的客户端
    default:
      coreSize: 10