server:
  port: 8989
management:
  security:
    enabled: false
# 服务端实现
spring:
  application:
    name: yd-yx-config
  cloud:
    config:
      server:
        git:
#           uri: file:///D:/workspace/config-repo
         uri: https://github.com/HuaYuAI/config-repo
#          timeout: 4
#          skipSslValidation: false
#          username: trolley
#          password: strongpassword

