spring:
  application:
    name: ydyx-gateway
server:
  port: 9000
# 安全失效
management:
  security:
    enabled: false
# 取消服务器自我注册
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
# 服务用于注册
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka
